### ISSUE TITLE
Cannot read latest data file ('ObjectNullMultiple256' object has no attribute 'class_info')

### ISSUE THREAD

**Issue by Impending-Disaster** [pistacuro/binx#4]
Binx cannot read the latest datafile for Last Origin as of the latest patch on 2020-01-16/17

python binx.py -x .\translated.csv .\data.bin
INFO:root:Reading binary file...
71%
Traceback (most recent call last):
  File "binx.py", line 19, in <module>
    main(args)
  File "D:\Games\LastOrigin_Modding\binx-current\binx\__init__.py", line 108, in main
    read_binary_file(args.bin_file_path)
  File "D:\Games\LastOrigin_Modding\binx-current\binx\__init__.py", line 96, in read_binary_file
    if rte_object.class_info.object_id not in rte_objects:
AttributeError: 'ObjectNullMultiple256' object has no attribute 'class_info'

**Comment by Impending-Disaster** [comment]
Should be solved in PR #5 , there seems to be an unhandled ObjectMultipleNull256 inside of the BinaryArray class.

**Comment by BeepedWhenIShouldaBooped** [comment]
Should be solved in PR #5 , there seems to be an unhandled ObjectMultipleNull256 inside of the BinaryArray class.

**Comment by pistacuro** [comment]
@Impending-Disaster @BeepedWhenIShouldaBooped sorry for letting you hanging for so long. Real life is taking most of my time. @BeepedWhenIShouldaBooped thanks for the patch. The #5 is merged now. I will try to fix/merge stuff sooner from now on... :)
